version: "3.8"

services:
  nuxt-app:
    profiles: ["app"]
    image: node:22
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://amaya:amaya@postgres:5432/amaya

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: amaya
      POSTGRES_PASSWORD: amaya
      POSTGRES_DB: amaya
    volumes:
      - amaya-postgres:/var/lib/postgresql/data

volumes:
  amaya-postgres:
